name: Build and Deploy Streamlit App to Azure Web App - Sign-Lang

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip cache purge || true

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r *.py requirements.txt deploy/
          cp -r model_weights/ deploy/ || true
          cp -r images/ deploy/ || true
          cp -r Video/ deploy/ || true
          cp -r custom.onnx deploy/ || true
          cd deploy && zip -r ../app.zip .

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: app-package
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0060845211AD4D4DBC56E85DBD1D0805 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4CB21689FC15479D89C747FF696EE34C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48C44834A5024BD58F48FED3B4853A7D }}

      - name: Deploy to Azure Web App using Oryx build
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Sign-Lang'
          slot-name: 'Production'
          package: app.zip
          runtime-stack: 'PYTHON|3.9'

      - name: Set Streamlit startup command
        run: |
          az webapp config set \
            --name Sign-Lang \
            --resource-group <YOUR_RESOURCE_GROUP_NAME> \
            --startup-file "python3 -m streamlit run streamlit_app.py --server.port 8000 --server.address 0.0.0.0"
