name: Build and deploy Python app to Azure Web App - Sign-Lang

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Validate requirements file
        run: |
          echo "Checking requirements.txt..."
          pip install -r requirements.txt --dry-run || true

      - name: Upload source for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/
            !__pycache__/
            !.venv/
            !*.pyc
            !*.pyo
            !*.pyd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0060845211AD4D4DBC56E85DBD1D0805 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4CB21689FC15479D89C747FF696EE34C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48C44834A5024BD58F48FED3B4853A7D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Sign-Lang'
          slot-name: 'Production'
          package: ''
